### ISSUE TITLE
Both xsel and fallback failed when running headless

### ISSUE THREAD

**Issue by akomakom** [ff6347/to-markdown-cli#217]
I am not familiar with `xsel`, so it was not obvious to me that `html2md` would not work in `tmux` by default.  (Needing a display is not obvious) 

I had to run the command via `DISPLAY=:0 html2md ...` to get it to work.  Perhaps other people will encounter this too, probably should be added to the README

**Comment by ff6347** [comment]
Hm. Nice find I guess it is related to the copy to clipboard functionality.

**Comment by ff6347** [comment]
@akomakom If you create a PR with the README information I would be pretty happy.
