### ISSUE TITLE
Feature Request - Please provide turndown options as cli flag

### ISSUE THREAD

**Issue by codeRSH** [ff6347/to-markdown-cli#258]
Thank you for making this cli tool. However, it would be more useful if turndown options could be provided as flags or may be picked from a config file so that we can produce the markdown in the format that we want. 

Thanks.

**Comment by ff6347** [comment]
Hi @codeRSH nice idea. I would go for having a global config file that gets overwritten by a local one before implementing all turndown features flags. Using XDG config folders https://wiki.archlinux.org/title/XDG_Base_Directory and with cosmicconfig https://github.com/cosmiconfig/cosmiconfig for loading configs. 

Are you willing to contribute?

**Comment by ff6347** [comment]
Looks like cosmic config does not support XDG folders yet. 🤔 

https://github.com/cosmiconfig/cosmiconfig/issues/152

Hopefully it will be implemented.
